version: '3.8'

services:
  postgres-airflow-standalone:
    image: postgres:13
    container_name: postgres-airflow-standalone
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-standalone:
    image: apache/airflow:2.10.4
    container_name: airflow-standalone
    ports:
      - "9097:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow-standalone/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False" # Use as string para variáveis de ambiente
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      postgres-airflow-standalone:
        condition: service_healthy # Garante que o PostgreSQL esteja saudável antes de iniciar o Airflow
    command: bash -c "airflow db init && airflow users create --username airflow --firstname airflow --lastname airflow --role Admin --email airflow@admin.com --password airflow && airflow standalone"